spring.application.name=veebipood
server.port=8090

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d79b1onkijhs738rjj20-a.oregon-postgres.render.com/veebipood_database_lten
spring.datasource.username=veebipood_user
spring.datasource.password=55XPd0N0P9MaYPzGW6rj6BUwqMaqV84A