#Render database connection
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d811alfaqgkc73aigdog-a.oregon-postgres.render.com/veebipood_database_z063
spring.datasource.username=veebipood_user
spring.datasource.password=EDPC4WyQldNO7d4gHJfx7890zClXrdyD